### ISSUE TITLE
Ninja 1.10 compatibility for fortran / lapack

### ISSUE THREAD

**Issue by lanodan** [michaelforney/samurai#101] opened 2023-11-04 10:07 UTC
Similar kind of issue to <https://github.com/michaelforney/samurai/issues/99> but instead it's fortran and ninja 1.10+

```
CMake Error at CMakeLists.txt:3 (project):
  The Ninja generator does not support Fortran using Ninja version

    1.9

  due to lack of required features.  Ninja 1.10 or higher is required.
```

**Comment by orbea** [comment] 2023-11-29 00:50
Duplicate of issue https://github.com/michaelforney/samurai/issues/36.

**Comment by orlitzky** [comment] 2024-10-20 15:48
Needed for SuiteSparse now as well, e.g. https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev/SuiteSparse_config/cmake_modules/SuiteSparsePolicy.cmake

**Comment by michaelforney** [comment] 2024-12-06 21:21
Closing as duplicate of #36.

**Closed by michaelforney** 2024-12-06 21:21 UTC
